---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[rvm::default]
      - recipe[rvm::rubies]
    attributes:
      rvm:
        user:
          name: vagrant
          password: vagrant
        rubies:
          version: 2.2.3
