---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.11' }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[rvm_sl::user_install]
      - recipe[rvm_sl::rubies]
    attributes:
      rvm_sl:
        user:
          name: vagrant
          password: vagrant
        rubies:
          version: 2.2.3
