---
driver_config:
  digitalocean_api_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.04
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rvm_sl::rubies_test]
    attributes:
      rvm:
        user:
          name: vagrant
          home: '/home/vagrant'
