language: ruby
rvm:
- 2.2.3
sudo: false
addons:
  apt:
    sources:
    - chef-current-precise
    packages:
    - chefdk
env:
  global:
  - CI=true
  - secure: aMVmmQ2AgE9rYr1POyPKLuibOdD8tNHVijYUtU6C1lIwlsn8pOTY7cdpzpVEOd51GA7JjZE8u/+k/C5tMBOqgNguB9ZlNN7gfgpZZl5y2uaz3vU2zm9PQvuFOuBIwhaS3xYAPtgTfQEHIhSPJahhXbMcBYFlu8GtwZJbjy2fi/c57m08y+0tBZiQFHg19EfNcOFUJQnB1nYWaWXM0f/BzibZ6O8xVDRZlnfGQeYLOPRZ6/ygxOx6bs+fpPIfJQJ0BXKwaX1D8031oQ05YBiWYbdLiV3Zj0iRrj74d82OylFGTAEtKVidh4361VoJcvWNf2Hwilkc+/fvTrqGWmCxBqggPpYEks+VWGm7+xMTXsndJ5SoW5Fx1QnPxRL8Yf2WQ8D97WMYA2PFJBFxnRrkUGd4RWalPXPCwFg3pAzW6IQL37B7kGxAJrjgPSyBDTpVtqDDZFraBxiFY5ZP3yvltGZ2Kkd1c6EKMCAXtrYPUixgNRX3mzicEI7K/1x9O7zuj1W/OV77vC066ydPVaVhYhCkN0AoVMtVVYVxBQWuWDrin3z1sHbltjb7tagxGwfAJpYecrU5Aajg4nIeQZMLR62Ta7esHfX2FiUfvHJ4yit5z/udM/BS664v+JN8p6NiSJK+jiO/sLdy5xXH+teH6YrT42M7q2FwPpnBytvGiKU=
  - secure: haXxZ7gIX0wHOFjnbo8O4x+wGZLoX78VpR68pvxJoxeXqc0g8DiWdvrOE7Vduyb+w9NyFBCCNnleneAPEvfyVm48bNTso0YQriuG6ZE41k+7CYHpe1ZxD8oBI3gra/wmSDhR+CVBj1naC7MtRgvyzjx2UFgPgWpXNXs7A2FW3ffJ0L6GUEpaEbhMSqBYYLmqmSp0mkf7w9fuUbXVWRP3aP9Eokl4kRk/XlJEHhDKG/iIRdLu+3wD2SRHiUiG8hjR8f+Jeps+o8bPwIt5XUCbcqEa0mcFZWdJGzE6naRLkiIoS594hdQv7eeLmGdlqE5tbyzagOnwka/QQmK1IXiF2oDEmF28AanvfPUjeEcTgMCeVaylwKpdAT+7MNY8QXjablAVW3S5Lr3xHDpk0c5Ht8A5AZ1/I+81t8y8vt4+IZPBDyuZzDQnCSfbcC6NZQKBkPtMav0B3iSUSU3bxaCfwok+0C1LfZqdd+l7Qi3D+nF3RtllcnlH9A9KyBeJQ0vPTDk6flvxm8pEHTk7buXK0X/kAb91qB9uHTxZsX4YfopyfCxa+FJNC5EBP8Jox7j2n2IQa/I8SRxrIL8uv4Io/P4RCSx1e3LRgGh7HxZ+s6hlwU7FIEg3w2s4CYdi3MIp90auvI5GpM/DCy2gcpYOabwETwvh+uhWwO7366fXDqQ=
install:
- chef exec gem install bundler
- chef exec gem install nokogiri -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2
- chef exec bundle install --without development --without chef --without kitchen_vagrant
branches:
  only:
  - master
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- "/opt/chefdk/embedded/bin/chef gem install chef-sugar"
script:
- "/opt/chefdk/embedded/bin/chef --version"
- "/opt/chefdk/embedded/bin/rubocop --version"
- "/opt/chefdk/embedded/bin/rubocop"
- "/opt/chefdk/embedded/bin/foodcritic --version"
- "/opt/chefdk/embedded/bin/foodcritic . --exclude spec"
- "/opt/chefdk/embedded/bin/rspec spec"
- rake quality:all
- "/opt/chefdk/embedded/bin/kitchen test"
after_script:
- "/opt/chefdk/embedded/bin/kitchen destroy"
